from groq import Groq
MODEL = "openai/gpt-oss-20b"
client = Groq()
def evaluate_context(query, context):
    """
    Checks whether the retrieved context is relevant
    to the user's question.
    """
    prompt=f"""
You are evaluating a RAG system.

User question:
{query}

Retrieved context:
{context}

Does the retrieved context contain information
that is directly relevant to answering the question?

Give a score from 0 to 1
0 = completely irrelevant
0.5 = partially relevant
1 = highly relevant

Return ONLY the number.
"""
    response=client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )
    score=response.choices[0].message.content.strip()
    return score
def evaluate_answer(query, answer):
    """
    Checks whether the generated answer 
    directly answers the user's question.
    """
    prompt=f"""
You are evaluating the answer generated by a RAG system.
User question:
{query}
Generated answer:
{answer}

Does the generated answer directly and clearly
answer the user's question?
Give a score from 0 to 1.
0=does not answer the question
0.5 = partially answers the quesion
1=directly and completely answers the question

Return ONLY the number.
"""
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    score = response.choices[0].message.content.strip()

    return score

def evaluate_faithfulness(context, answer):
    prompt = f"""
You are evaluating the faithfulness of a RAG answer.

Retrieved context:
{context}

Generated answer:
{answer}

Does the answer contain claims that are supported by the retrieved context?

Give a score from 0 to 1.

0 = unsupported
0.5 = partially supported
1 = fully supported

Return ONLY the number.
"""

    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        print("Faithfulness evaluation failed:", e)
        return "N/A"