from groq import Groq
MODEL = "openai/gpt-oss-20b"
client = Groq()
def evaluate_context(query, context):
    """
    Checks whether the retrieved context is relevant
    to the user's question.
    """
    prompt=f"""
You are evaluating a RAG system.

User question:
{query}

Retrieved context:
{context}

Does the retrieved context contain information
that is directly relevant to answering the question?

Give a score from 0 to 1
0 = completely irrelevant
0.5 = partially relevant
1 = highly relevant

Return ONLY the number.
"""
    response=client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role":"user",
                "content":prompt
            }
        ]
    )
    score=response.choices[0].message.content.strip()
    return score
def evaluate_answer(query, answer):
    """
    Checks whether the generated answer 
    directly answers the user's question.
    """
    prompt=f"""
You are evaluating the answer generated by a RAG system.
User question:
{query}
Generated answer:
{answer}

Does the generated answer directly and clearly
answer the user's question?
Give a score from 0 to 1.
0=does not answer the question
0.5 = partially answers the quesion
1=directly and completely answers the question

Return ONLY the number.
"""
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    score = response.choices[0].message.content.strip()

    return score


def evaluate_faithfulness(context, answer):
    """
    Checks whether the claims in the generated answer 
    are supported by the retrieved context.
    """
    prompt=f"""
You are evaluating the faithfulness of a RAG system.

Retrieved context:
{context}
Generated answer:
{answer}

Break the generated answer into its main factual claims.

For each claim, determine whether it is directly supported by the retrieved context.

Calculate a faithfulness score from 0 to 1:

1 = all important claims are directly supported
0.75 = most claims are supported
0.5 = about half of the claims are supported
0.25 = very few claims are supported
0 = none of the claims are supported

Important:
- Do NOT use general knowledge.
- Do NOT assume information that is not present in the context.
- A claim must be supported by the retrieved context itself.
- Do not judge writing quality or answer relevance.

Return ONLY the final numerical score.
"""
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    score = response.choices[0].message.content.strip()

    return score

